apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pipelines-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-csi"
  resources:
    requests:
      storage: 10Gi
  volumeName: open-webui-pipelines-volume
