apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-pipelines-volume
  namespace: ollama
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: "192.168.1.125"
    path: "/share/NFS/open-webui-pipelines"
