apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-csi"
  resources:
    requests:
      storage: 100Gi
  volumeName: open-webui-volume
