apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-volume
  namespace: ollama
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs-csi"
  nfs:
    server: "192.168.1.125"
    path: "/share/NFS/ollama"
